all: date uptime cal main

date: date.c
	gcc -o date date.c

uptime: uptime.c
	gcc -o uptime uptime.c

cal: cal.c
	gcc -o cal cal.c

main: main.c
	gcc -o main main.c

clean:
	rm -f date uptime cal main

